######################################################################
# Automatically generated by qmake (3.1) Fri Sep 20 15:51:46 2019
######################################################################

TEMPLATE = app
TARGET = PlugConsole
INCLUDEPATH += .

# Input
HEADERS += PlugConsole.h
FORMS += PlugConsole.ui
SOURCES += main.cpp PlugConsole.cpp
RESOURCES += PlugConsole.qrc
